name: Node.js CI
'on':
  - push
  - pull_request
jobs:
  build:
    name: 'Test [Node.js v${{ matrix.node_version }} / ${{ matrix.os }}]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 10
          - 12
          - 14
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          version: '${{ matrix.node_version }}'
      - uses: bahmutov/npm-install@v1
      - name: test
        run: npm test
